version: "3.8"

services:
  db:
    image: postgres:15
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB:   ${PGDATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT:-5432}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-backend
    depends_on:
      - db
    environment:
      PORT:       ${PORT}
      PGHOST:     db
      PGUSER:     ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT:     5432
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./:/usr/src/app
    command: npm run dev

volumes:
  db_data:
